kasa_spoleczna={1:"Wymieniasz elektrykę w swoich nieruchomościach. Zapłać: 40 ECTS za każdy komputer,115 ECTS za każdą pracownie.",
2:"Zająłeś 2 miejsce w konkursie piękności. Pobierz 50 ECTS",
3:"Błąd bankowy na twoim koncie! Pobierz 200 ECTS",
4:"Wyjdź bezpłatnie z więzienia. (Tę kartę możesz zatrzymać do późniejszego wykorzystania lub sprzedaży)",
5:"Idź do więzienia. Nie przechodź przez START. Nie pobieraj 200 ECTS",
6:"Masz urodziny! Pobierz 10 ECTS od każdego gracza.",
7:"Fundusz Zdrowotny. Pobierz 100 ECTS",
8:"Zapłać za wizytę u dentysty - 100 ECTS",
9:"Zapłać czesne 50 ECTS",
10:"Przejdź na START ( Pobierz 200 ECTS )",
11:"Wyprzedaż! Pobierz 50 ECTS",
12:"Zapłać za wizytę Lekarską - 50 ECTS",
13:"Zwrot podatku. Pobierz 20 ECTS",
14:"Otrzymujesz 25 ECTS za porady finansowe",
15:"Odziedziczyłeś spadek. Pobierz 100 ECTS",
16:"Dostałeś premię! Pobierz 100 ECTS"}